# Generated by Django 5.2.8 on 2025-11-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
