# Generated by Django 5.2.7 on 2025-11-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf', '0011_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Paid', 'Paid'), ('Failed', 'Failed')], default='Pending', max_length=50),
        ),
    ]
